# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/grpc_api/authentication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'services/grpc_api/authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&services/grpc_api/authentication.proto\x12!society_connect.authentication.v1\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x90\x01\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x15\n\rrefresh_token\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x10\n\x08username\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t2\x83\x01\n\x15\x41uthenticationService\x12j\n\x05Login\x12/.society_connect.authentication.v1.LoginRequest\x1a\x30.society_connect.authentication.v1.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.grpc_api.authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=77
  _globals['_LOGINREQUEST']._serialized_end=127
  _globals['_LOGINRESPONSE']._serialized_start=130
  _globals['_LOGINRESPONSE']._serialized_end=274
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=277
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
