export const ROUTES = {
  dashboard: '/',
  login: '/login',
  members: '/members',
  memberNew: '/members/new',
  memberDetail: (id: string) => `/members/${id}`,
  memberEdit: (id: string) => `/members/${id}/edit`,
  memberDetailPattern: '/members/:id',
  memberEditPattern: '/members/:id/edit',
  books: '/books',
  bookNew: '/books/new',
  bookDetail: (id: string) => `/books/${id}`,
  bookEdit: (id: string) => `/books/${id}/edit`,
  bookDetailPattern: '/books/:id',
  bookEditPattern: '/books/:id/edit',
  categories: '/categories',
  categoryNew: '/categories/new',
  categoryDetail: (id: string) => `/categories/${id}`,
  categoryEdit: (id: string) => `/categories/${id}/edit`,
  categoryDetailPattern: '/categories/:id',
  categoryEditPattern: '/categories/:id/edit',
  borrow: '/borrow',
  lendings: '/lendings',
  overdue: '/overdue',
} as const;

export const API_PATHS = {
  csrf: '/auth/csrf/',
  login: '/auth/login/',
  refresh: '/auth/refresh/',
  logout: '/auth/logout/',
  currentUser: '/auth/me/',
  books: '/books/',
  bookOptions: '/books/options/',
  book: (id: string) => `/books/${id}/`,
  categories: '/categories/',
  categoryOptions: '/categories/options/',
  category: (id: string) => `/categories/${id}/`,
  members: '/members/',
  memberOptions: '/members/options/',
  member: (id: string) => `/members/${id}/`,
  memberBorrowedBooks: (id: string) => `/members/${id}/borrowed-books/`,
  borrow: '/lending/borrow/',
  lendings: '/lending/',
  returnBook: (id: string) => `/lending/${id}/return/`,
  overdue: '/lending/overdue/',
  dashboardSummary: '/dashboard/summary/',
} as const;
